-- db_setup.sql

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_uuid VARCHAR(50) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  user_group ENUM('ALT1-GRP1','ALT1-GRP2','ALT1-GRP3','ALT1-GRP4') DEFAULT 'ALT1-GRP1'
);

CREATE TABLE IF NOT EXISTS city (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  postal_code VARCHAR(20) DEFAULT NULL,
  latitude DECIMAL(9,6) DEFAULT NULL,
  longitude DECIMAL(9,6) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS weather_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  city_id INT NOT NULL,
  last_update DATETIME NOT NULL,
  temperature FLOAT DEFAULT NULL,
  wind_speed FLOAT DEFAULT NULL,
  description VARCHAR(255) DEFAULT NULL,
  FOREIGN KEY (city_id) REFERENCES city(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS addresses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  city_id INT NOT NULL,
  address_label VARCHAR(255) DEFAULT 'Résidence',
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (city_id) REFERENCES city(id) ON DELETE CASCADE
);